### ISSUE TITLE
Why not compare disabled loggers?

### ISSUE THREAD

**Issue by ceki** [GoodforGod/java-logger-benchmark#5]
If I understand correctly, the benchmark configures output to the console and redirects the console to /dev/null. 

Why not disable logging at level INFO (the level the benchmark invokes logger printing methods)? That way the cost involved in printing to /dev/null via the console will be removed from the results.

**Comment by GoodforGod** [comment]
Do you mean setting logging level to WARN?

If it is so, than there will be nothing to benchmark actually, cause there always be instant return:
```
if(isInfoLoggingPossible) {
              // actual logic never executed
} else {
  return;     // always executed
}
```

The idea behind redirecting output to /dev/null is to eliminate costs of IO of the machine, cause IO is the most heavy part and in that case it is mostly benchmarking IO of the device, how it prints data to STDOUT and not the loggers implementations

So the trick with redirect actually allows to isolate real logic and all methods of loggers implementations to be invoked like it is real application and benchmark all of than while eliminating the effects of IO costs

**Comment by ceki** [comment]
Yes, setting the root logging level to WARN was what I had in mind.

By the way, thank you for the feedback. I think we are in agreement. 

Access to the console (System.out or System.err) is synchronized. So even writing to /dev/null will incur some processing which you might want exclude from your measurements. On the other hand, the benchmark takes into account the cost of creating a logging event and looping through appenders which is a very good idea.

Perhaps sending output to a NoOperationAppender would be the ideal approach?

**Comment by GoodforGod** [comment]
This is actually the idea also, I know that is synchronized and this access to IO should be measured, cause as you see from data some loggers have really different implementations, and such huge performance gaps actually occur due to some loggers accessing IO More frequently than the others, this is the main reason why they perform poorly when compared to others, cause IO is the most costly operation, so measuring access to System.out / System.err is intended by me.

And this behavior also reflects the real usage logger will have, in real application it will also access IO (System.out / System.err / etc) and will have all those penalties by poorly managing IO access, so that's what you can see from the results of all loggers.

Some accessing IO keeping in mind that it costs a lot, some accessing it More frequently and thoughtlessly, thus having poor performance compared to others. 
This is all intended behavior and what benchmark intends to uncover
